version: "3.8"

services:
  postgres:
    image: postgres:15.7
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db:
  cache:
